### ISSUE TITLE
create figure of pre-industrial versus projections

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/vin#12]
Step 1: Issue #11 
Step 2: Anomalize preindustrial run and all projections to **mean of preindustrial run**
Step 3: Plot preindustrial and all projections
Step 4: Also prepare and send .csv file of all the data that goes into this figure (the anomalized version of the data for each year of each run, and the means for each year of each run also)

**Comment by MoralesCastilla** [comment]
Now can be found in: ~\GitHub\vin\climatefuture\analyses\Pre.post.industrial.climate
Closing!
