### ISSUE TITLE
Quantifying regional effects by country (or similar)

### ISSUE THREAD

**Issue by MoralesCastilla** [lizzieinvancouver/vin#13]
Table for Supp. Mat. with effects (gains-losses) per country or larger geographic region. This will quantitatively support the visual description of the maps in Fig. 1. Allow introduce a sentence in the main text noting that:
"Main current growing regions, particularly in (Southern Europe and XX, and XX) are predicted to undergo major shifts in the varieties to grow."
The top producing countries are expected to gain ... and loose... 

Note: in the table we'll select the top producing countries (>2% of the total production).
Data coming from Anderson's to be found in `adelaide/analyses/adelaideanlyse.R`

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla 

Okay, how about adding these three to the three we have (Spain, Italy, France)?
(1) PNW: Oregon & Washington states
(2) California
(3) New South Whales, South Australia, Victoria (3 provinces in Australia)

If it really is easy we could also add, but don't do it if it takes too long (I imagine our co-authors will ask for other ones anyway):
(4) New Zealand
(5) Germany

**Comment by lizzieinvancouver** [comment]
done!
