### ISSUE TITLE
Add -20 threshold by days

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/vin#14]
Check the papers on minima temperatures for winegrapes and adjust how we account for -20 in our output. I should probably be something like 7/10 days below -20 C over 10 years means no grapes at all. But again, see what the papers did and perhaps err on the side of allowing the grapes to survive colder? Let Lizzie know what you find out and plan to do.

**Comment by MoralesCastilla** [comment]
After reading Iñaki's comments and seeing results based on 5 days below (-20C) within the 10 year temporal window (d866d2c489f36a7f6e6f3b607adf7aeae410aa3b), I would use this threshold. To be discussed.

**Comment by lizzieinvancouver** [comment]
Also, here's Iñaki's comments (email on 24 Oct 2017):

> Hi Lizzie and Nacho,
> 
> We also use this value as a threshold in STICS to define lethal temperature for grapevines. 
> To my knowledge one day with this temperature could be enough to kill the entire plant (in winter). In February or March, even if budbreak did not happen, maybe higher temperatures (-12°C) can have the  same effect (we saw it in 2012). 
> In fact it depends a lot of the type of training. In the areas where they have very low temperature (Hungary, China) they completely cover the plants with soil during wither and they uncover them in spring. 
> So, I think your indicator (5 days at -20°C in 10 years) is a good idea even if it is still probably quite conservative. Maybe 2 days is enough to consider that these areas cannot be adapted to viticulture.
> I hope these comments can help you
> All the best
> 
> Iñaki
> 
> 
> -----Message d'origine-----
> De : Elizabeth Wolkovich [mailto:lizzie@oeb.harvard.edu] 
> Envoyé : samedi 21 octobre 2017 00:04
> À : Ignacio Morales Castilla <moralescastilla@fas.harvard.edu>; Inaki Garcia de Cortazar Atauri <igarcia@avignon.inra.fr>
> Objet : Re: Moving along
> 
> Hi Nacho and Iñaki!
> 
> Nacho, having looked again at the refs (see below) I think your plan sounds good but I thought we should also loop in Iñaki.
> 
> Iñaki, Nacho and I want to add a minimum temperature for the projections since we currently have a lot of Siberia and Canada growing grapes ... 
> we think -20 C should be the cut off but we're struggling with how many days. Our current plan is to say grapes cannot grow in a region in a 10-year period if there are more than 5 days below -20 C (the days could one each year or all in one year).
> 
> Does this seem reasonable to you?
> 
> All the best,
> Lizzie

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla I think you can close this if you want! Nice work!

**Comment by MoralesCastilla** [comment]
We will reconsider re-opening the issue if anyone has concerns about the 5day @ -20C threshold chosen. Closing!
