### ISSUE TITLE
get change in veraison date for two regions

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/vin#22]
- Chard and Pinot for Burgundy
- Cab-Sauv and Merlot for Bordeaux
Get change in veraison dates and get % suitability for each var in each region during baseline period

**Comment by MoralesCastilla** [comment]
@lizzieinvancouver 
I have uploaded the Veraison shifts predicted for these regions and varieties (f06b5b9d12b8091d292ebc9524ce3a238c5ea8ea). Getting the % suitability during the baseline period now.

**Comment by lizzieinvancouver** [comment]
done.
