### ISSUE TITLE
stuff to do to send to co-authors

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/vin#27]
@MoralesCastilla 
(1) Re-do maps figure for 2C with C panel as largest, be sure to correct all things noted in #20 
(2) Give brief definition of climatic suitability in caption to Fig 1. 
(3) Make sure variety diversity figure is correct and update caption -- this should be the current winegrowing regions figure (make sure the axis says this)
(4) Add figures for temp-only models of climatic suitability to supp
(5) Add gains numbers to main text
(6) Add phenological diversity figure to supp (main text: While these varieties span a diversity of phenologies (see Supporting Information appendix XXXX) and make up..)
(7) Add some figures including the late ripening composite to supp.
(8) Check all numbers in main text!

**Comment by lizzieinvancouver** [comment]
(9) Add to supp how we define current growing regions.

**Comment by MoralesCastilla** [comment]
@lizzieinvancouver 

This is where I'm at with the above tasks. I will continue tomorrow.

(1) Re-do maps figure for 2C with C panel as largest, be sure to correct all things noted in #20
-done

(2) Give brief definition of climatic suitability in caption to Fig 1.
-done (perhaps it could be briefer) 

(3) Make sure variety diversity figure is correct and update caption -- this should be the current 
winegrowing regions figure (make sure the axis says this)
-done

(4) Add figures for temp-only models of climatic suitability to supp
-done, although we may want to include further temp-based results later.

(5) Add gains numbers to main text
- done (all numbers are in and commented out and the see line 169 and next, I have included the mention to the gains in paragraph starting on line 176. To be decided if we provide more numbers)

(6) Add phenological diversity figure to supp (main text: While these varieties span a diversity of phenologies (see Supporting Information appendix XXXX) and make up..)
- done 

(7) Add some figures including the late ripening composite to supp.
- in progress 

(9) Add to supp how we define current growing regions.
-done (may need further refinement)

(10) Check the equations in supp -- Lizzie mangled them.
-checked

(11) Add some figure showing current winegrowing regions.
-done

(13) We have conflicting numbers for what years we used for 2C and 4C in the Supp. Please check! Was is: 2039-2048 and 2076-2085 or 2081-2100 and 2041-2060?
-done (the 2081 comes from an older version).

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla 
Wow! Nice work. I will being working through the text today and probably tomorrow (given I don't have much time today). Hopefully we can get it out soon.

One thing you mentioned above that I don't see is the phenological diversity figure in the supp --  what page is it on? I think I am missing it.

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla 
I think we're very close! You've done an amazing amount of work and I tried to get through as much as I could but am still working on the supp. I will log some more hours tomorrow.

How is work going on some LCR figures? Will it be possible to add them soon?

A couple things I am hoping we could add/correct/check so the co-authors can understand what we did:

1. Table of model parameters
2. Simple table of data we used for building models
3. Figure or two of model validation (Napa?) results
4. Quick text on how we selected locations for niche envelopes (how many points? What did we do when a variety had more points than we could include so as to keep things even across varieties)?
5. How many GCM model members did we have? 30 or 32? I have contrasting notes but can update this if you tell me.
6. Please check my text at the start of phenological modeling in the supp. Are these the correct cold cut-offs?
7. My biggest question is if we had a cut-off of suitability for building the data beyond fig 1. We show >25% there but did we only use 75% for the rest of the results? How did this work? (Sorry I forget but it's a critical point.)
8. Add Fig 1 version for 4C to supp.
9. Please also confirm the changes I made before to the climate data section of supp (we used two datasets to parameterize the models and went forward with the BEST estimates, correct?!)

For the adding the table I added an *example* table to show how to do it from R. Hopefully this will make it easy to put together some simple tables quickly, but let me know if you're having trouble with Sweave.

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla 
Things to remember to send to and tell co-authors:
(1) other options for fig. with varieties (one with other order, one with negative #s)
(2) we're OVER on word count so if they want to suggest additions, we'd appreciate deletion options too (if possible).
... more I imagine!

**Comment by lizzieinvancouver** [comment]
**Another thing**: check gains for Pinot and Chasselas -- My naive guess is that at 4C a bunch of new regions open up in the Northern hemisphere in places with big land masses  ... and just the earliest varieties make it there but we need to check if that is true. And we probably need to note this in the main text.

**Comment by MoralesCastilla** [comment]
@lizzieinvancouver 

Here goes the latest update.
1. Table of model parameters
done but table S2 needs tweaking, I've been struggling to compile in sweave (it doesn't source using the same protocol in mac and PC and thus I had to change the R chunk).

2. Simple table of data we used for building models
In progress

3. Figure or two of model validation (Napa?) results
done, but we may want to upload more and I need to improve png quality

4. Quick text on how we selected locations for niche envelopes (how many points? What did we do when a variety had more points than we could include so as to keep things even across varieties)?
done

5. How many GCM model members did we have? 30 or 32? I have contrasting notes but can update this if you tell me.
This is commented out in the supp. we used 30, but 3 out of those have systematically failed. I can keep on trying while coauthors revise the ms.

6. Please check my text at the start of phenological modeling in the supp. Are these the correct cold cut-offs?
Checked. cut-offs seem correct.

7. My biggest question is if we had a cut-off of suitability for building the data beyond fig 1. We show >25% there but did we only use 75% for the rest of the results? How did this work? (Sorry I forget but it's a critical point.)
Gains and losses figures are built using two thresholds:
- a 75% threshold for each maturity model (6 out of 8 climatic variables must meet the imposed conditions)
- a 50% "uncertainty" threshold meaning that at least 185 runs (GCMxyears) must meet the criteria for a given variety to be considered as present at a given site.

8. Add Fig 1 version for 4C to supp.
Done

9. Please also confirm the changes I made before to the climate data section of supp (we used two datasets to parameterize the models and went forward with the BEST estimates, correct?!)
These changes seem correct. I have to add a paragraph on our bias correction procedure through which we correct the bias in our GCMs to conform them to BEST data, which is what we utilize for model parameterization.


Another thing: check gains for Pinot and Chasselas -- My naive guess is that at 4C a bunch of new regions open up in the Northern hemisphere in places with big land masses ... and just the earliest varieties make it there but we need to check if that is true. And we probably need to note this in the main text.
Your guess is right, or so it seems by looking at the maps.

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla 
Talk to you soon but here's where I think we're at:

1. I think I fixed the tables, take a look. I also adjusted the one so we don't have repeating numbers.
2. I got the two documents to cross-reference the labels! So we can use \ref across the sup and main text. I inputted a lot of these.

(a) Simple table of data we used for building models
(b) We're missing a Supp figure on the REASONS for losses. We reference it a lot in the main text so could we add one?
(c) LRC
(d) Some dangling text about gains to finish in Supp I think.

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla 

I think you can submit when you want after fixing in the supp:
(1) Add the real Cayan et al. 2010 ref to bibtext and then add the \citep to:
	(1) third paragraph of supp
	(2) Fig S5: Napa
	(3) Fig S6: Napa
(2) cites for MaxEnt, Random Forests
(3) bioclimatic envelopes WHAT percent in this sentence: the target variety represented at least \% of the total extension planted for that variety
I don't need to see it again before you submit, but see my email (sending in a sec for a few reminders). And from above:
Things to remember to send to and tell co-authors:
(1) other options for fig. with varieties (one with other order, one with negative #s)
(2) we're OVER on word count so if they want to suggest additions, we'd appreciate deletion options too (if possible).
... more I imagine!
