### ISSUE TITLE
summary of co-author comments to deal with

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/vin#36]
**Kees:**
1. Small comments in main text to incorporate. 
2. Number of specific, important (but addressable) comments in the supp. NOTE: His comment on climatic suitability is probably driven in part by the fact that we used data from MANY areas to calibrate the envelopes.

**Ben:**
1. Table of BEST vs local weather station parameters for models (see other issue for Nacho)
2. Be sure to remove mention of years in main text (and in supp, where appropriate) -- focus on warming levels
3. Correct affiliation and name

**Thierry:**
1. Small spelling errors (subsp. not subsps.) and Mourvedre --> Monastrell
2. Need estimates of vineyard age (need to work on, I emailed Andy Walker)
3. Add references and note to desynchronization

**Kim:**
1. Lots of small tweaks to improve manuscript throughout that I think we can easily do
2. Be more consistent in language (increase/decrease); also wants to focus on 'saving' (not sure if that is critical, could use another opinion ... see quote below)
3. How many significant digits?
4. Agrodiversity or agrobiodiversity? We should be consistent!
5. Define resilence
6. State % of current winegrowing regions that our models capture?
7. Stress more the extremes matter? See quote below.
8. Suggestions for Fig 1. (some quotes below)
9. Suggestions for Fig 3. (many notes, see file)
10. Fig 2: Make it more clear what the model climatic suitability represents in the caption.

> One question is how to frame the variable reported, it seems to me to sometimes be % remaining suitable land (counting up from 0) and sometimes amount of land lost from a baseline (counting down from 100). I think this should be consistent. For me, I think the simplest would be to take the baseline modeled suitable area under 0° as 100%, and report the amount of potentially suitable area remaining under +2 and +4° . The most important numbers to me are those vs. today’s currently planted wine regions. This would lead to a "saved" framing (60% saved vs 40% lost). Personally I like this more positive spin but we have to acknowledge large losses :( 

> overall I thought the increase in extremes (rather than averages/GDDs) as a driver was interesting and could be emphasized  more, this shows that it is important to study/model these and not just old measurements of averages- this might deserve a paragraph (at least in the supp) relevant for crop modeling generally. though would need slight rephrasing as increase in min temp is not an extreme. 

> Fig 1: clarify if this is only the modeled climactic suitability, and/or show actual growing regions today (either delineated in eg darker grey on this map, or just mask out non-regions today). Basically let the reader interpret how big of a difference this is from today, relative to where wine is grown today.

**Comment by lizzieinvancouver** [comment]
**Iñaki's comments (in person: 28 June 2018):**
change to all means or medians in Fig 2 and related text
reduce the use of relative losses (and/or add a figure to show these numbers)
add an explanation of how relative losses are calculated

**Comment by lizzieinvancouver** [comment]
Some general figure changes we decided to make:

**Fig 1:**
a) cultivar diversity at 0C 
b) current winegrowing regions
c) culativar diversity at 2C (currently 1b)
d) Pinot at 50+75% (drop 25%) versus green for all gained land from 11 vars (50% or higher)
e) turnover (current figure 1c)

**Fig 2:**
a) Change the caption to be more clear about uncertainty
b) Change from median to mean for the horizontal bars.

**Fig. 3**
a) change the caption to figure 3 to address Kim's comments and Kees' comments 
b) make background colors versus bands more different

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla I think you can close this once you confirm we did Iñaki's 1. comment above: change to all means or medians in Fig 2 and related text

**Comment by MoralesCastilla** [comment]
@lizzieinvancouver The text used means, and I already changed all figures, closing!
