### ISSUE TITLE
add explanation to the climate envelopes factors

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/vin#39]
Explain what we expect with each one (add citations if possible)

**Comment by lizzieinvancouver** [comment]
Done, just need to ask Amber and Kees to check what we have.

**Comment by MoralesCastilla** [comment]
@lizzieinvancouver 
I have updated Kees comments on the environmental factors (still in need for a citation justifying the GDD above 25, which Kees suggests that Iñaki or Amber may provide).

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla I think we can close whenever you like. Maybe just email Iñaki about *if* we need a ref to that 25 C or can just 'say see XX section above'.
