### ISSUE TITLE
Warming thresholds

### ISSUE THREAD

**Issue by MoralesCastilla** [lizzieinvancouver/vin#4]
Instead of RCPs or years -- adopt the trend in the field (in line with Paris) and use warming thresholds of +1C, +2C, +4C. To do so:

- Compute pre-industrial global average temperature to be used as baseline 
- Compute each year's avg warming relative to baseline.
- Use decades or years leading to such increase.

**Comment by MoralesCastilla** [comment]
After comparing pre-industrial climate (pre 1850 climate) against post industrial climate, we have chosen the following decades as representative for the following warming thresholds:

1970-1979 -> increase of temperature of 0.064 (~0C) - we'll use this as baseline. Then we'll use models for the following periods representative of warming thresholds:
Period                  warming
2015 - 2024         1.028 ~ 1C
2039 - 2048         2.026 ~ 2C
2058 - 2067         3.030 ~ 3C
2076 - 2085         4.003 ~ 4C

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla This is great! Thanks for all your efforts on it. I really like the approach. One question -- should we do 1.5 C instead of 1? I think 1.5 is the Paris Agreement (see http://unfccc.int/paris_agreement/items/9485.php)?

**Comment by MoralesCastilla** [comment]
@lizzieinvancouver Sure, let's do that, then the period for 1.5 is:
2028 - 2037         1.528 ~ 1.5C
Does that sound reasonable?

**Comment by bcook** [comment]
This is fine! I still think we should do 2 degrees and 4 degrees, but it will be interesting to see if there are really substantive differences between 1.5 and 2.

Before we do anything else, I just want to see the pooled distributions of temperatures for all years across the ensemble for each threshold. Just to get a sense for what the spread looks like.

**Comment by MoralesCastilla** [comment]
We are going with 2 and 4.
