### ISSUE TITLE
fix late-ripening composite

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/vin#40]
- check that the parameters were correctly calculated (did we maybe subtract when we should have added)

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla This seems close but the table (S3) is still wrong. Can you update? Also change: Late Ripening Cultivar to Late-ripening composite

**Comment by MoralesCastilla** [comment]
@lizzieinvancouver 
This has been done now. We can close when you check it is ok.

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla Looks good, close when you want!
