### ISSUE TITLE
change figures 1-3 in main text

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/vin#42]
**Fig 1:**
a) cultivar diversity at 0C
b) current winegrowing regions
c) culativar diversity at 2C (currently 1b)
d) Pinot at 50+75% (drop 25%) versus green for all gained land from 11 vars (50% or higher)
e) turnover (current figure 1c)
Rep above for equivalent supp figure. 

**Fig 2:**
a) Change from median to mean for the horizontal bars.
b) Change the caption to be more clear about uncertainty and how losses are calculated (Lizzie)

**Fig. 3**
a) change the caption to figure 3 to address Kim's comments and Kees' comments (Lizzie)
b) make background colors versus bands more different

**Comment by MoralesCastilla** [comment]
@lizzieinvancouver 

This is done and uploaded to Git, I'm closing the issue.
