### ISSUE TITLE
table of BEST vs local weather station parameters for models

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/vin#43]
Needed for supp.

**Comment by MoralesCastilla** [comment]
I have included tables S4 and S5 to the Supplements with the comparison of parameters. Once you check they are in the desired format, we can close this issue

**Comment by lizzieinvancouver** [comment]
Great! I will keep an eye out for the push.

**Comment by lizzieinvancouver** [comment]
Done!
