### ISSUE TITLE
change all figures to Monastrell

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/vin#46]

**Comment by MoralesCastilla** [comment]
This has been done, but it will be good to re-check before closing the issue to make sure there are no mourvedre remaining.

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla Looks close -- figure S12 should be changed, and the tables S1 and S3 need fixing. I did the text so you can close with the Fig S12 and Tables S1, S3 are done!

**Comment by MoralesCastilla** [comment]
Fig S12, and Tables S1 and S3 have been fixed. I'm closing, yaiii!!
