### ISSUE TITLE
figure on drivers of region loss

### ISSUE THREAD

**Issue by MoralesCastilla** [lizzieinvancouver/vin#5]
Include veraison comparison between baseline and future and compute amount of cells lost due to a late veraison (delaying of phenology).

**Comment by lizzieinvancouver** [comment]
add reasons and directionality for losses and gains for Pinot noir and CabSauv

**Comment by lizzieinvancouver** [comment]
also gather data on veraison date change for regions lost and region gained (could be text or table)

**Comment by lizzieinvancouver** [comment]
done!
