### ISSUE TITLE
cultivar diversity figures

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/vin#51]
Iñaki wrote: 

> Figure S15 and S16 [these are the % loss of regions versus cultivar diversity] – it could be useful to add reference values of the previous figures (figure 2 and S11) in order to show the differences between both (at least maximum and minimum values of loss% with an small star) 

... seems tricky without confusing readers, any ideas on how to implement?

**Comment by MoralesCastilla** [comment]
@lizzieinvancouver 
I have tried to add stars to the values of new fig s11 (see commit). I'm not super happy about it, perhaps we should leave max/min values only as Iñaki suggests?

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla I agree this doesn't seem to work -- having all the figures together in the supp is a good change though. Close this issue whenever you want.
