### ISSUE TITLE
Make sure caption for data validation is correct.... 

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/vin#53]
Our models estimate: 50% budburst, flowering and veraison. 

**Our comparison data ...**
RUML: Four phenological stages of grapevine were examined for the period 1986–2011: the beginning of budburst – the date when green shoot tips became just visible, identified as stage 7 on the BBCH scale (Lorenz et al. 1995); the beginning of flowering – the date when first flower hoods are detached from the receptacle (stage 60 on the BBCH scale); the beginning of veraison – the date when berries begin to develop cultivar-specific colour (stage 81 on the BBCH scale); and harvest (stage 89 on the BBCH scale).

MALEIRO: These phenological stages were considered to occur when 50 % of the plants had reached a particular stage. Budburst, flowering and veraison correspond to stages 07, 65 and 81, according to the BBCH scale, respectively (Lorenz et al., 1995).

BOCK: Recorded phenophases included budburst (BBCH 09: green shoot tips clearly visible), full flowering (BBCH 65: 50% of flowerhoods fallen), véraison (BBCH 81: colour change and initial matu- ration of the grape) and harvest (BBCH 89: berries ripe for harvest).

**Comment by lizzieinvancouver** [comment]
Note that:
mod EL 23 = BBCH 65
mo EL 35 = BBCH 81

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla 

Hi Nacho, can you check your notes or ask Amber what Eichorn Lorenz stage our data used for budbreak? 

Then I will try to wrap up this issue.

**Comment by MoralesCastilla** [comment]
I have written Amber an email asking for this info. Thanks!

**Comment by lizzieinvancouver** [comment]
From Amber:

`Lizzie,

 

I’m forwarding Amber’s response to the EL query. Let me know if I can help with this.

 

Best,

 

Nacho

 

From: Parker, Amber <Amber.Parker@lincoln.ac.nz>
Sent: Thursday, August 2, 2018 10:07 PM
To: Ignacio Morales Castilla <moralescastilla@fas.harvard.edu>
Subject: RE: Quick question

 

Hi Ignacio

 

Great to hear from you! The manuscript looks great and I look forward to seeing the next version.


We use EL 4 –green tip; first leaf visible as our stage for Budburst (woolly bud is much harder to observe).

 

All the bes

Amber

 `

**Comment by lizzieinvancouver** [comment]
Okay, I think this is done, see commit: 9b5b52e3ed80b6d6bb576e3774821d85158254c
