### ISSUE TITLE
Extend climate niche envelopes?

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/vin#8]
Extend from -10% to 110% and see how it changes answer? Or -20% to 120%?

**Comment by lizzieinclass** [comment]
Only do all additional analyses like this (where we are testing the impact of some choice we made) on Europe!

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla Wait, is this really done?

**Comment by lizzieinvancouver** [comment]
We'll number of indicators! As noted in Supp so closing.
